begin;
do $$
declare actor uuid; cid uuid; org uuid; lib jsonb; payload jsonb; aid uuid; rid uuid; req uuid; sid uuid; dayid uuid; leader uuid; q uuid; ar jsonb; other_actor uuid; other_org uuid; fid uuid; stats jsonb; doc jsonb; n int:=0;
begin
 select id into actor from auth.users where raw_app_meta_data->>'platform_role'='admin' limit 1;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 select id into org from public.organizations where status='active' limit 1;
 select id into cid from public.audit_types where active limit 1;
 lib:=public.checklist_library('new','{}');rid:=(lib->>'id')::uuid;
 payload:='{"header":{"name":"Teste de execução","category":"custom"},"reason":"Teste com rollback","sections":[{"title":"Seção","requirements":[{"reference":"4.1","prompt":"Requisito","questions":[{"prompt":"Pergunta A"},{"prompt":"Pergunta B"},{"prompt":"Pergunta C"}]}]}],"lock_version":0}'::jsonb;
 payload:=payload||jsonb_build_object('revision_id',rid);
 payload:=jsonb_set(payload,'{sections,0,criterion_id}',to_jsonb(cid));
 lib:=public.checklist_library('publish',payload);req:=(lib->'sections'->0->'requirements'->0->>'id')::uuid;
 payload:=public.audit_workspace('create',jsonb_build_object('organization_id',org,'type_id',cid,'title','Teste com rollback','scope','Validação transacional'));
 aid:=(payload->>'id')::uuid;
 perform public.checklist_execution('confirm',jsonb_build_object('audit_id',aid,'revisions',jsonb_build_array(rid)));
 select leader_membership_id into leader from public.audits where id=aid;
 perform public.audit_workspace('team_save',jsonb_build_object('audit_id',aid,'members',jsonb_build_array(jsonb_build_object('id',leader))));
 perform public.audit_workspace('plan_save',jsonb_build_object('audit_id',aid,'lock_version',(select lock_version from public.audits where id=aid),'items',jsonb_build_array(jsonb_build_object('title','Atividade','date','2026-10-07','process','Processo A','requirements',jsonb_build_array(req)))));
 perform public.audit_workspace('plan_publish',jsonb_build_object('audit_id',aid,'lock_version',(select lock_version from public.audits where id=aid),'reason','Teste'));
 select id into dayid from public.audit_days where audit_id=aid;
 select id into sid from public.schedule_items where audit_day_id=dayid;
 perform public.audit_workspace('start',jsonb_build_object('audit_id',aid));
 perform public.audit_workspace('attendance',jsonb_build_object('audit_id',aid,'day_id',dayid,'members',jsonb_build_array(leader)));
 perform public.checklist_execution('suggest',jsonb_build_object('audit_id',aid));
 perform public.checklist_execution('questions',jsonb_build_object('audit_id',aid,'schedule_id',sid));

 perform public.checklist_execution('filters',jsonb_build_object('audit_id',aid));
 perform public.checklist_execution('scope_catalog',jsonb_build_object('audit_id',aid,'schedule_id',sid));
 perform public.checklist_execution('evidence_catalog',jsonb_build_object('audit_id',aid));
 perform public.checklist_execution('findings',jsonb_build_object('audit_id',aid));
 perform public.checklist_execution('history',jsonb_build_object('audit_id',aid));
 select id into q from public.checklist_questions where requirement_id=req order by sort_order limit 1;
 perform public.checklist_execution('scope_exclude',jsonb_build_object('audit_id',aid,'schedule_id',sid,'question_id',q,'reason','Exclusão rastreável de teste'));
 assert (public.audit_workspace_stats(aid)->>'total')::int=2;
 perform public.checklist_execution('scope_include',jsonb_build_object('audit_id',aid,'schedule_id',sid,'question_id',q,'reason','Reinclusão rastreável de teste'));
 assert (public.audit_workspace_stats(aid)->>'total')::int=3;
 payload:=jsonb_build_object('audit_id',aid,'schedule_id',sid,'question_id',q,'lock_version',0,'operation_id',gen_random_uuid(),'patch',jsonb_build_object('result','conforming','evidence_text','Registro','sampling','no'));
 ar:=public.checklist_execution('save',payload);
 perform public.checklist_execution('complement',jsonb_build_object('audit_id',aid,'assessment_id',ar->>'id','prompt','Questão de teste','reason','Teste','response','Resposta','operation_id',gen_random_uuid()));
 select id into fid from public.assessment_complements where assessment_id=(ar->>'id')::uuid;
 perform public.checklist_execution('complement_response',jsonb_build_object('audit_id',aid,'assessment_id',ar->>'id','id',fid,'response','Resposta revisada','lock_version',0));
 doc:=public.checklist_execution('independent',jsonb_build_object('audit_id',aid,'schedule_id',sid,'complement_id',fid,'prompt','Item independente','reason','Novo escopo aprovado','confirm_scope',true,'operation_id',gen_random_uuid()));
 assert (public.audit_workspace_stats(aid)->>'total')::int=4;
 perform public.checklist_execution('save',jsonb_build_object('audit_id',aid,'schedule_id',sid,'question_id',doc->>'id','lock_version',0,'operation_id',gen_random_uuid(),'patch',jsonb_build_object('evidence_text','Extra')));
 lib:=public.checklist_library('incorporate',jsonb_build_object('complement_id',fid,'revision_id',rid,'reference','4.1','prompt','Pergunta revisada e genérica','reviewed',true));
 assert lib->>'status'='draft';
 assert (select count(*) from public.checklist_questions where requirement_id=req)=3,'Modelo original modificado';
 lib:=public.checklist_library('outline',jsonb_build_object('revision_id',lib->>'id'));
 assert (lib->'sections'->0->>'unloaded')::boolean;
 lib:=public.checklist_library('save',jsonb_build_object('revision_id',lib->>'id','lock_version',lib->'lock_version','header',lib->'header','sections',lib->'sections','components',lib->'components','reason','Salvar sem carregar seção'));
 assert jsonb_array_length(lib->'sections'->0->'requirements'->0->'questions')=4,'Seção não carregada foi perdida';
 perform public.checklist_execution('upload_begin',jsonb_build_object('audit_id',aid,'assessment_id',ar->>'id','operation_id',q,'filename','foto.png'));
 begin perform public.checklist_execution('complete',payload||jsonb_build_object('lock_version',1,'operation_id',gen_random_uuid()));raise exception 'TEST: upload pendente ignorado';exception when raise_exception then if sqlerrm='TEST: upload pendente ignorado' then raise;end if;end;
 perform public.checklist_execution('upload_state',jsonb_build_object('audit_id',aid,'assessment_id',ar->>'id','operation_id',q,'status','cancelled','reason','Teste'));
 ar:=public.checklist_execution('complete',payload||jsonb_build_object('lock_version',1,'operation_id',gen_random_uuid()));
 ar:=public.checklist_execution('reopen',payload||jsonb_build_object('lock_version',2,'operation_id',gen_random_uuid(),'reason','Revisão técnica'));
 assert ar->>'operational_state'='in_progress';
 assert (select count(*) from public.checklist_record_history where audit_id=aid)>3;
end $$;
rollback;
